### ISSUE TITLE
iHealth Wave (AM4) incompatibility on LG Android phones

### ISSUE THREAD

**Issue by cody-griffin** [iHealthDeviceLabs/iHealthDeviceLabs-Android#69]
According to https://ihealthlabs.com/support/fitness-devices/ihealth-wave/, the iHealth Wave is supported on only select devices using Android 4.0 or later. 

Using the iHealth SDK, the iHealth Wave is able to connect to and appears to function correctly with a Samsung Galaxy S8, Samsung Galaxy J3, and Moto G4. However, it does not with various LG devices such as the LG G5, LG V20, and LG Aristo MS210.

Is this general incompatibility with LG devices a function of the iHealth SDK excluding them? Or is it a function a hardware incompatibility between the phone and the iHealth Wave?

Any information you can provide would be incredibly helpful. Thank you.

**Comment by jialiabc** [comment]
hello cody-griffin 

Connection will fail on Android 7.0 with devices as follows:
AM4   Firmware Version < 1.4.4

You need update the Android version to 7.1

Could you please check if it is known issue first?

**Comment by cody-griffin** [comment]
jialiabc,

I do not believe that is correct as I was just able to pair an iHealth Wave (AM4) on Firmware Version 1.3.7 with my Samsung Galaxy S8 that is on Android version 7.0.

**Comment by jialiabc** [comment]
hello cody-griffin,

Different phone companies maybe add some modifications when they release.

You can try:
1. update the Android version to 7.1
2. update AM4 Firmware Version >= 1.4.4

**Comment by cody-griffin** [comment]
jialiabc,

Unfortunately, I do not have those devices available at the moment to test. However, based on your responses, it sounds as if you suspect their is some sort of manufacturer specific modification from LG on top of Android 7.0 causing the incompatibility with iHealth Wave (AM4) on a Firmware Version below 1.4.4. Is this correct? Has iHealth actually tested this statement?

**Comment by jialiabc** [comment]
Hello cody-griffin,

As we test, Connect will fail on Android 7.0 with devices as follows(you can refer to the FAQ):

1. HS4  Firmware Version < 1.0.5
2. PO3  (Firmware Version < 1.0.5   ||  (Firmware Version = 1.0.5  && Display Version != 11.0.5))
3. PO3M Firmware Version < 2.1.4
4. BP3L  （Firmware Version =1.0.0 && BT Version < 1.2.4）
5. KN-550BT  (Firmware Version =1.0.0 && BT Version < 1.2.4）
6. AM3   All the version
7. AM3S   Firmware Version < 1.1.8
8. AM4   Firmware Version < 1.4.4

So if your Samsung mobile phones can connect successfully, that may because Samsung  add some modifications when they release Android 7.0 ROM.

**Comment by cody-griffin** [comment]
Thank you for the clarification.
